// Generated by CoffeeScript 1.10.0
(function() {
  $.fn.DragMultiSelect = function() {
    var $this, items, items_status, lastIndex, movedFlag, selectedFlag, selectingFlag, startIndex, triggerCount;
    selectingFlag = false;
    selectedFlag = false;
    startIndex = -1;
    lastIndex = -1;
    movedFlag = false;
    items_status = [];
    $this = $(this);
    items = $this.children();
    triggerCount = function() {
      var count, i, item, len;
      count = 0;
      for (i = 0, len = items.length; i < len; i++) {
        item = items[i];
        if ($(item).hasClass("selected")) {
          count += 1;
        }
      }
      return $this.trigger("DragMultiSelectEvent", [count]);
    };
    items.on("mousedown touchstart", function(event) {
      var i, index, item, len, results;
      event.preventDefault();
      movedFlag = false;
      selectingFlag = true;
      $this = $(this);
      selectedFlag = !$this.hasClass("selected");
      startIndex = items.index($this);
      results = [];
      for (index = i = 0, len = items.length; i < len; index = ++i) {
        item = items[index];
        results.push(items_status[index] = $(item).hasClass("selected"));
      }
      return results;
    }).on("mouseup touchend", function(event) {
      selectingFlag = false;
      if (!movedFlag && items.index($(this)) === startIndex) {
        $(this).toggleClass("selected");
      }
      movedFlag = false;
      return triggerCount();
    }).on("mousemove touchmove", function(event) {
      var endIndex, i, index, ref;
      movedFlag = true;
      if (selectingFlag) {
        endIndex = items.index($(this));
        for (index = i = 0, ref = items.length; 0 <= ref ? i < ref : i > ref; index = 0 <= ref ? ++i : --i) {
          if ((index <= endIndex && index >= startIndex) || (index >= endIndex && index <= startIndex)) {
            $(items[index]).toggleClass("selected", selectedFlag);
          } else {
            $(items[index]).toggleClass("selected", items_status[index]);
          }
        }
      }
      if (lastIndex !== endIndex) {
        triggerCount();
        return lastIndex = endIndex;
      }
    });
    return this;
  };

}).call(this);

//# sourceMappingURL=DragMultiSelect.js.map
