// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var refresh;
    refresh = function() {
      return $.getJSON("/browse", {
        path: $("#path").val()
      }, function(data) {
        var $container, dragMultiSelect, e, i, j, len;
        $container = $("#container");
        $container.empty();
        for (j = 0, len = data.length; j < len; j++) {
          i = data[j];
          e = encodeURIComponent(i);
          $("<div>").addClass('item').attr("path", i).css("background-image", "url(/file?path=" + e + ")").appendTo($container);
        }
        $("#count").attr("data-badge", 0);
        dragMultiSelect = $("#container").DragMultiSelect();
        return dragMultiSelect.on("DragMultiSelectEvent", function(event, count) {
          return $("#count").attr("data-badge", count);
        });
      });
    };
    $("#go").on("click", function() {
      var dragMultiSelect, i, j;
      if ($("#path").val() === "") {
        for (i = j = 0; j < 40; i = ++j) {
          $("<div>").addClass('item').appendTo($("#container"));
        }
        dragMultiSelect = $("#container").DragMultiSelect();
        return dragMultiSelect.on("DragMultiSelectEvent", function(event, count) {
          return $("#count").attr("data-badge", count);
        });
      } else {
        return refresh();
      }
    });
    return $("#delete").on("click", function() {
      var $item, item, j, len, ref, selection;
      selection = [];
      ref = $("#container").children();
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        $item = $(item);
        if ($item.hasClass("selected")) {
          selection.push($item.attr("path"));
        }
      }
      return $.ajax({
        url: "/delete",
        data: {
          paths: selection
        },
        method: "POST",
        success: function() {
          return refresh();
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=demo.js.map
