// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    return $("#go").on("click", function() {
      var dragMultiSelect, i, j;
      if ($("#path").val() === "") {
        for (i = j = 0; j < 40; i = ++j) {
          $("<div>").addClass('item').appendTo($("#container"));
        }
        dragMultiSelect = $("#container").DragMultiSelect();
        return dragMultiSelect.on("DragMultiSelectEvent", function(event, count) {
          return $("#count").attr("data-badge", count);
        });
      } else {
        return $.getJSON("/browse", {
          path: $("#path").val()
        }, function(data) {
          var $container, e, k, len;
          $container = $("#container");
          $container.empty();
          for (k = 0, len = data.length; k < len; k++) {
            i = data[k];
            e = encodeURIComponent(i);
            $("<div>").addClass('item').attr("id", e).css("background-image", "url(/file?path=" + e + ")").appendTo($container);
          }
          $("#count").attr("data-badge", 0);
          dragMultiSelect = $("#container").DragMultiSelect();
          return dragMultiSelect.on("DragMultiSelectEvent", function(event, count) {
            return $("#count").attr("data-badge", count);
          });
        });
      }
    });
  });

}).call(this);

//# sourceMappingURL=demo.js.map
