// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var i, j;
    for (i = j = 0; j < 20; i = ++j) {
      $("<div>").addClass('item').html('233').appendTo($("#container"));
    }
    return $("#container").DragMultiSelect();
  });

}).call(this);

//# sourceMappingURL=demo.js.map
